### ISSUE TITLE
Adding script for images of cat with breed and description

### ISSUE THREAD

**Issue by josenino95** [UCSB-Library-Research-Data-Services/intro2APIs#1]
In the "What is an API?" section you say "With a bit of coding, we can display the image of the cat:". I think it would be cool if you can add an hyperlink here to the code snippet you used for creating the image. This would be nice for those attendees that know about programming but are just discovering APIs. The hyperlink could go to a script file stored in this repo, and it could be in any programming language you already used for creating the image.

**Comment by jairomelo** [comment]
Great! Now code snippets are visible to users if they want.
